
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/bytedance/cocoapods_sdk_source_repo.git'
source 'https://github.com/volcengine/volcengine-specs.git'

platform :ios, '9.0'

target 'VOLCDemo' do    
  pod 'TTSDK', '1.23.2.1-premium', :subspecs => ['Player']
  pod 'VEPlayerUIModule', :path=> './VEPlayerUIModule/'
  pod 'Masonry'
  pod 'SDWebImage'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'Reachability'
  pod 'MJRefresh'
  
end

# post_install do |installer|
#   installer.pods_project.build_configurations.each do |config|
#   config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
#   end
# end
